variable "db_name" {}
variable "db_type" {}
variable "project" {}
variable "location" {}
variable "resource_group_name" {}
variable "sku_name" {}
variable "sku_capacity" {}
variable "sku_tier" {}
variable "sku_family" {}
variable "storage_mb" {}
variable "backup_retention_days" {}
variable "geo_redundant_backup" {}
variable "db_useradmin" {}
variable "db_password" {}
variable "db_version" {}
